apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-05-31T05:39:27Z"
  name: red
  namespace: default
  resourceVersion: "940"
  uid: b682d7e0-a8fa-4217-836a-c65838305479
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: red-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tvgb4
      readOnly: true
  initContainers:
  - name: red
    image: busybox
    command: ['sleep','20']
--- 
#  another init container 
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: red-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tvgb4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - sh
    - -c
    - sleep 20
    image: busybox
    imagePullPolicy: Always
    name: red